name: Vernaillen PNPM CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest] # macos-latest, windows-latest
        node: [20]
    
    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo Hello from Vernaillen
